language: java
jdk:
- oraclejdk7
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
script:
- mvn versioneye:update test
env:
  global:
  - secure: BWN8E9wCGoqIskLdD/SDafCYyrQKd4D3DvBmeUghXKQsxbRXf5XKj8/QeiIcZyLOACT5LByZs+pguLgoZwjYIDCWkrNWcCV7dLT0iPp/v/pEMr6kcR1JbCsHKZJPImpNIVOtCfTXmlxCTagE7E9HoNFsfFyuQqVxXNjlqWWG180G66Glm5ucUQmZR5oM/QO/lUZnYIELK9riaxe3vFsLMjH0yOlYwbtOUSfJaiqo0Zr4pjkDAlEz8YJ3zzCHfsHedOuURbkNDxptRUyGf9nwiF+02onJGDdcmMTLJp4eeWHDKBnUZdGjEWMN9m4EO8m2bTDD75dRI/r2V+Tjv6EWWCV3NBBJeUj547kMRLHkDmxWzC0BKNKDn1Vtr95xub4Ej66bbULDGGaldAvwDJorNWFiLmCS/wHdfg1AyGNBP0ZT4lN4IrJVct156uylV6rGVvQy+fy8sZ4oNWn6PSC6nARpiHOkufcPr6U3OdtNJz4fOQrVI9xn3AiCfMBjE8inOSUhsJLfrP/BSZ3/KyId+BCjlEENwMbA/47wCSpIxySw57R65ij45iwhdXnFpgX87JXiwXfwcymco2VBnsglc3ERDE+EoPn5ZhJzcrRkRR7xhgrGgyqGTKX4Lro0px9i3jHXHdm/AxBDeTluBt4OTg8PRqv9j8XxduYxdaIlAUg=
  - secure: Mt6WAncluKN5k+8p7IwJO64ihNiA3jTqY4g16gWOGLF9/SLhpEgAe0fj1oW6yaPl8/+bZwxYu7sajoh1BH6IIWqeQ55HvHxwdpk4KBS03LLLCNU9AXLHJYhThMk/mVd4k8jvvTLevGah3sw4EX/v/6W97+uA7vwxQkCOHB0U2H7xNDfasL8m1fPfwx0bRuX6XjDuWj1mV8Od8JdZOHCeQdZMjUqMLw5mxJT3aG/6sPOKs+FBfjelU0+DXGdidP/DTwXBGpNY0/Wtugl12+LZSuruW1OyrNtV6QVc2vm5JcQU+ppEic9kErlZigotFc6MbRerH3gCgr7auA3xcau7+JPRZ3z/x+UDpuAhfUK8rhO1XOcMQQOiJZgQjzBK9KWUiCRgPrZyKyf8YPmY60cFVGnzKLK1uQJk+OgD1NBBSH3TdOUn/cr4ZkfK1uehnCZYxI23S00hYsI4lHF/Y2DOMRxwrd0Mzjif/8W9xim9n6ZlKGyyILVDuvwR9jia4mtmQmlHFJOArklwLeQK5EnkinX9oHPSxAbf9JybOBO2UmZtIL5IFI4FwjVqyKpHV+fEAT7yAE86jhTxSLtTxsAy+YRuOytPZcKdqiu+/sV5dUprQVq0dWgj5ewNjI5YuSHzgW37nMyRpSN0Sk32utREZMV44JhK8L2ud0CfVcOEG4E=
