language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
before_install:
- export LANG=fr_FR.UTF-8
- export TZ=Pacific/Noumea
install:
- mvn install -DcreateChecksum=true -DSkipTests=true -Dmaven.javadoc.skip=true
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/ROOT*.jar)
- export RELEASE_PKG_MD5_FILE=$(ls target/ROOT*.jar.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/ROOT*.jar.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: DMjqD2jkHQZCufwCTHs7LK2w0uR1h5C8Wtjc2k3AqO/K0hfp3d4FB/FJKz2WrA79pueoaxAXwwpl/5QL9gZbo8I/GabZX6Mc73THjD7dPSNTKsgorwV1cF3Vkn8096dpGpxHoxIFJTmqaYDAHe6MhMoyI7/3lzTvLKx61Yd86V0NmM52hEP/SKFJA43HNsxV3sw3Vw/BElFTnCkvgfkO83KSPl95dIEo3Q5JSUQO10WLBUK7ROGEEuGegGYS/Gj85s1ARgbdMyEB8uv5mYxjNMFxatM11/O0CkonwNqSn2bWDwuIpXiCHkAatjrZ/8X9bamArqy78lIoq1oxHB0eZGWUGNkt/gDiAvzCUPrw5d4yRdBc+AH6jEm1RLdvwY5f2otY7nkvABmk3NCUZTiyuw97Eqks1Fkmi58oX3ouVmvUop0rTwohJoK6DaQN+l5XIdjG8kefEeN5MwRb074q/r2+mJxQIO1QIkjLBjaf5ePwy4c5dCNxDQlAmJI+FWAccI9Z7g+l0+kKm58wu1BbTUQmyOhkm1RBa7bnCWK68Q1dcwGL5B/ZNvXaGm29MLDx4fdiNWEv0SOd6RguOJHGx3j9eF8F/9i9tXrz+2HFmXfK8umvnvW4SWfphV4mCYRm3sVto3ilpFihqMkIshAcU8pMYtfHCJ1EPxe+2bOVIOo=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/dassdeces
